import type { Metadata } from "next";
import Navbar from "../Components/Navbar";
import Footer from "../Components/Footer";
import "./globals.css";

import { JetBrains_Mono, Righteous } from 'next/font/google';

// Configure the fonts
const jetBrainsMono = JetBrains_Mono({
  subsets: ['latin'],
  variable: '--font-jetbrains-mono',
});

const righteous = Righteous({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-righteous',
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="schema-dark">
      <body className={`${jetBrainsMono.variable} ${righteous.variable} bg-[#0f0f0f] text-white grid place-items-center`}>
        <Navbar/>
        <div className="container xl:max-w-[1200px] pt-[5rem]">{children}</div>
        <Footer/>
        </body>
    </html>
  );
}
