import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Narayan",
  description: "Generated by ammar",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="schema-dark">
      <head>
        <title>Narayan</title>
        <link rel="icon" href="/assets/nav-icon.png" />
      </head>
      <body>{children}</body>
    </html>
  );
}
